# Generated by Django 4.1.1 on 2022-10-05 12:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, max_length=10, null=True)),
                ('longitude', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'Location',
                'unique_together': {('longitude', 'latitude')},
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weather.location')),
            ],
            options={
                'verbose_name': 'Weather Data',
                'verbose_name_plural': 'Weather Datas',
                'db_table': 'weather_data',
            },
        ),
    ]
