# Generated by Django 4.1.1 on 2022-10-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_weatherdata_location_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.CharField(default=0.0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.CharField(default=0.0, max_length=10),
            preserve_default=False,
        ),
    ]
